# Generated by Django 5.0.2 on 2025-10-24 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificación',
            },
        ),
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('recordatorio_pago', '📅 Recordatorio de Pago'), ('pago_confirmado', '✅ Pago Confirmado'), ('cliente_moroso', '⚠️ Cliente Moroso'), ('soporte_tecnico', '🔧 Soporte Técnico'), ('promocion', '🎯 Promoción'), ('bienvenida', '👋 Mensaje de Bienvenida')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField(help_text='Usar variables: {nombre}, {deuda}, {fecha_limite}, {servicio}')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recordatorio_pago', '📅 Recordatorio de Pago'), ('pago_confirmado', '✅ Pago Confirmado'), ('cliente_moroso', '⚠️ Cliente Moroso'), ('soporte_tecnico', '🔧 Soporte Técnico'), ('promocion', '🎯 Promoción'), ('bienvenida', '👋 Mensaje de Bienvenida')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('enviado', '✅ Enviado'), ('fallido', '❌ Fallido'), ('programado', '📅 Programado')], default='pendiente', max_length=10)),
                ('programada_para', models.DateTimeField(blank=True, null=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('modificada_en', models.DateTimeField(auto_now=True)),
                ('id_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.cliente')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['estado', 'programada_para'], name='notificacio_estado_1a9076_idx'), models.Index(fields=['cliente', 'tipo'], name='notificacio_cliente_fc8caf_idx')],
            },
        ),
    ]
