# Generated by Django 5.0.2 on 2025-10-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('zonas', '0004_alter_zona_options_zona_cobrador_zona_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('respuesta_api', models.TextField(blank=True, null=True, verbose_name='Respuesta de la API')),
            ],
            options={
                'verbose_name': 'Registro de Envío',
                'verbose_name_plural': 'Registros de Envío',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionNotificacion',
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='plantillanotificacion',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Plantilla de Notificación', 'verbose_name_plural': 'Plantillas de Notificaciones'},
        ),
        migrations.RemoveIndex(
            model_name='notificacion',
            name='notificacio_estado_1a9076_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificacion',
            name='notificacio_cliente_fc8caf_idx',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='creada_en',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='enviada_en',
            new_name='fecha_envio',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='programada_para',
            new_name='fecha_lectura',
        ),
        migrations.RenameField(
            model_name='plantillanotificacion',
            old_name='creada_en',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='creada_por',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='error',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='id_externo',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='modificada_en',
        ),
        migrations.RemoveField(
            model_name='plantillanotificacion',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='plantillanotificacion',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='plantillanotificacion',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='error_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Error'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='intentos_envio',
            field=models.IntegerField(default=0, verbose_name='Intentos de Envío'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='notificaciones.plantillanotificacion'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='zonas.zona'),
        ),
        migrations.AddField(
            model_name='plantillanotificacion',
            name='contenido',
            field=models.TextField(default='', help_text='Puedes usar variables como {{nombre}}, {{monto}}, etc.', verbose_name='Contenido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantillanotificacion',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillanotificacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='canal',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Correo Electrónico'), ('sms', 'SMS')], default='whatsapp', max_length=20, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('leido', 'Leído')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pago', 'Recordatorio de Pago'), ('vencimiento', 'Aviso de Vencimiento'), ('confirmacion', 'Confirmación de Pago'), ('promocion', 'Promoción'), ('soporte', 'Soporte Técnico'), ('general', 'Mensaje General')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='plantillanotificacion',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='plantillanotificacion',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Plantilla'),
        ),
        migrations.AlterField(
            model_name='plantillanotificacion',
            name='tipo',
            field=models.CharField(choices=[('pago', 'Recordatorio de Pago'), ('vencimiento', 'Aviso de Vencimiento'), ('confirmacion', 'Confirmación de Pago'), ('promocion', 'Promoción'), ('soporte', 'Soporte Técnico'), ('general', 'Mensaje General')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='registroenvio',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_envio', to='notificaciones.notificacion'),
        ),
    ]
