# Generated by Django 5.0.2 on 2025-10-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
