# Generated by Django 5.0.2 on 2025-10-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_zona_activa_alter_zona_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
