# Generated by Django 5.0.2 on 2025-10-24 01:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0003_alter_zona_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['nombre'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.AddField(
            model_name='zona',
            name='cobrador',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'cobrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zona',
            name='codigo',
            field=models.CharField(default='Z001', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zona',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zona',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
