# Generated by Django 5.0.2 on 2025-10-24 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('derivada', 'Derivada a agente')], default='activa', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('satisfaccion', models.IntegerField(blank=True, help_text='Calificación 1-5', null=True)),
                ('agente_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_chatbot', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Conversación Chatbot',
                'verbose_name_plural': 'Conversaciones Chatbot',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('categoria', models.CharField(choices=[('pagos', '💳 Pagos y Facturación'), ('tecnico', '🔧 Soporte Técnico'), ('servicio', '📡 Servicio Internet'), ('general', '❓ Consultas Generales'), ('cuenta', '👤 Gestión de Cuenta')], default='general', max_length=20)),
                ('palabras_clave', models.TextField(help_text='Palabras clave separadas por coma para búsqueda')),
                ('activa', models.BooleanField(default=True)),
                ('veces_consultada', models.PositiveIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['categoria', 'veces_consultada'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('bot', 'Chatbot'), ('agente', 'Agente Humano')], max_length=10)),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chatbot.conversacionchatbot')),
                ('pregunta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.preguntafrecuente')),
            ],
            options={
                'verbose_name': 'Mensaje Chatbot',
                'verbose_name_plural': 'Mensajes Chatbot',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', '🟢 Baja'), ('media', '🟡 Media'), ('alta', '🔴 Alta'), ('urgente', '⚡ Urgente')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('abierto', '📝 Abierto'), ('en_progreso', '🔨 En Progreso'), ('esperando_cliente', '⏳ Esperando Cliente'), ('resuelto', '✅ Resuelto'), ('cerrado', '🔒 Cerrado')], default='abierto', max_length=20)),
                ('categoria', models.CharField(choices=[('pagos', '💳 Pagos y Facturación'), ('tecnico', '🔧 Soporte Técnico'), ('servicio', '📡 Servicio Internet'), ('general', '❓ Consultas Generales'), ('cuenta', '👤 Gestión de Cuenta')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('agente_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='chatbot.conversacionchatbot')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('detalles', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='chatbot.ticketsoporte')),
            ],
            options={
                'verbose_name': 'Historial de Ticket',
                'verbose_name_plural': 'Historial de Tickets',
                'ordering': ['-timestamp'],
            },
        ),
    ]
