# Generated by Django 5.0.2 on 2025-10-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='zona',
        ),
    ]
