# Generated by Django 5.0.2 on 2025-10-24 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('ingresos', 'Reporte de Ingresos'), ('morosos', 'Reporte de Clientes Morosos'), ('pagos', 'Reporte de Pagos'), ('clientes', 'Reporte de Clientes')], max_length=20)),
                ('parametros', models.JSONField(default=dict)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
