# Generated by Django 5.0.2 on 2025-10-24 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '0004_alter_zona_options_zona_cobrador_zona_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC')),
                ('telefono_principal', models.CharField(max_length=15)),
                ('telefono_secundario', models.CharField(blank=True, max_length=15)),
                ('direccion', models.TextField()),
                ('referencia', models.TextField(blank=True, verbose_name='Referencia de domicilio')),
                ('fecha_instalacion', models.DateField(verbose_name='Fecha de instalación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('moroso', 'Moroso'), ('suspendido', 'Suspendido')], default='activo', max_length=10)),
                ('plan_contratado', models.CharField(default='Plan Básico', max_length=100)),
                ('velocidad', models.CharField(default='10 Mbps', max_length=50)),
                ('deuda_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['admin', 'oficina']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zonas.zona', verbose_name='Zona asignada')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
                'indexes': [models.Index(fields=['dni'], name='clientes_cl_dni_5e5da9_idx'), models.Index(fields=['estado'], name='clientes_cl_estado_54796b_idx'), models.Index(fields=['zona'], name='clientes_cl_zona_id_5f7775_idx')],
            },
        ),
    ]
